# Q. Create a 3x3x3 array with random values

In [2]:
import numpy as np
d=np.random.randn(3,3,3)
d

array([[[ 0.33423979,  0.37525649,  0.21989924],
        [-0.92115651,  0.07721435,  1.78542316],
        [-0.08378094, -1.80283894, -0.50546166]],

       [[ 0.27889972,  1.40618839, -2.39074336],
        [-1.02244065, -0.51875127,  0.24065484],
        [-0.36293259,  1.21790509,  1.24560949]],

       [[-1.02062679,  0.588218  , -1.49367701],
        [-0.69791331, -1.59280275, -0.75845422],
        [-0.43026238,  1.31744315,  0.46588971]]])

# Q. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
d1=np.array([[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]])
print(d1)


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [4]:
d1[1][0]=1

d1

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [5]:
d1[2][1]=2
d1

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 2, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [6]:
d1[3][2]=3
d1

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 2, 5, 5, 5],
       [5, 5, 3, 5, 5],
       [5, 5, 5, 5, 5]])

In [7]:
d1[4][3]=4
d1

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 2, 5, 5, 5],
       [5, 5, 3, 5, 5],
       [5, 5, 5, 4, 5]])

In [8]:
d1

array([[5, 5, 5, 5, 5],
       [1, 5, 5, 5, 5],
       [5, 2, 5, 5, 5],
       [5, 5, 3, 5, 5],
       [5, 5, 5, 4, 5]])

# Q. Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
import numpy as np
d7=np.zeros((8,8))
print(d7)

d7[1::2,::2]=1
d7[::2,1::2]=1
d7

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# Q. Normalize a 5x5 random matrix

In [11]:
y=np.random.randn(5,5)

y=(y-np.mean(y))/(np.std(y))
y

array([[ 0.79004021,  0.83451623, -1.22664316, -0.23603382,  0.51514577],
       [-1.30288921,  0.59285634, -1.43281939,  0.03056748,  1.48201249],
       [-0.03789627, -1.66601626, -0.99721629,  0.68016347,  0.77990994],
       [ 2.11233441, -1.00130033, -0.63436277, -0.0545195 ,  0.29033109],
       [ 1.53256051,  0.26422395,  0.4749911 , -1.40077485, -0.38918115]])

# Q 5. How to find common values between two arrays?

In [28]:
n=np.array([[1,2,3,4,5],[7,8,87,10,11]])
m=np.array([[15,12,3,4,25],[72,87,19,10,11]])
print(m)
print(n)

[[15 12  3  4 25]
 [72 87 19 10 11]]
[[ 1  2  3  4  5]
 [ 7  8 87 10 11]]


In [29]:
z=np.intersect1d(n,m)
z
        

array([ 3,  4, 10, 11, 87])

# Q 6.How to get the dates of yesterday, today and tomorrow?

In [31]:
y=np.datetime64("today")-np.timedelta64(1)
t=np.datetime64("today")
t1=np.datetime64("today")+np.timedelta64(1)

print(y)
print(t)
print(t1)


2020-07-29
2020-07-30
2020-07-31


# Q 7. Consider two random array A and B, check if they are equal

In [52]:
t=np.random.randn(3,3)
q=np.random.randn(3,3)
print(t)
print(q)

equal = np.array_equal(t,q)
equal

[[ 0.33695776  1.22219273  0.03965966]
 [ 2.09847316 -0.89120999 -0.07155393]
 [-0.47501    -3.32923949 -0.86085985]]
[[-0.74368851  0.38253153 -0.4040641 ]
 [ 0.67953959  1.05223233 -0.98342859]
 [-0.39498978 -0.48767939 -0.84504926]]


False

# Q8 Create random vector of size 10 and replace the maximum value by 0

In [62]:
a=np.random.randn(10)
print(a)

max(a)

a[a.argmax()]=0
print(a)


[-0.26411314 -1.56182266 -0.27420289 -0.44762472  0.86042254  0.25973318
  0.22995061  0.40501568  0.46862911 -1.73902854]
[-0.26411314 -1.56182266 -0.27420289 -0.44762472  0.          0.25973318
  0.22995061  0.40501568  0.46862911 -1.73902854]


# Q9. How to print all the values of an array?

In [63]:
s=np.zeros((8,8))
s

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# Q10.Subtract the mean of each row of a matrix

In [68]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-0.29268622  0.31978511 -0.41082447 -0.09946197  0.39306137  0.23594623
   0.00459698 -0.5078659   0.38737143 -0.02992257]
 [-0.11980496  0.37603508  0.19070458  0.32407865 -0.44381662 -0.11939708
   0.17008628 -0.56068902 -0.06623708  0.24904017]
 [-0.16709729  0.68892464 -0.26086698  0.03411993 -0.01373502 -0.2314931
   0.23721693 -0.16861024 -0.23080836  0.1123495 ]
 [ 0.02154827 -0.48521973  0.24972103  0.19539151  0.01033334 -0.40523244
   0.08757114  0.09379324  0.35140295 -0.11930931]
 [-0.43585053 -0.32003747  0.14611932 -0.06607065  0.37777377 -0.00310494
   0.38279643 -0.37475827 -0.01679471  0.30992707]]
[[-0.29268622  0.31978511 -0.41082447 -0.09946197  0.39306137  0.23594623
   0.00459698 -0.5078659   0.38737143 -0.02992257]
 [-0.11980496  0.37603508  0.19070458  0.32407865 -0.44381662 -0.11939708
   0.17008628 -0.56068902 -0.06623708  0.24904017]
 [-0.16709729  0.68892464 -0.26086698  0.03411993 -0.01373502 -0.2314931
   0.23721693 -0.16861024 -0.23080836  0.1123495 ]
 


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [66]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 6. 5. 1. 3. 1. 5. 1. 2. 3.]


In [67]:
np.add.at(Z, I, 1)
print(Z)

[ 5. 11.  9.  1.  5.  1.  9.  1.  3.  5.]



 # Q 12.How to get the diagonal of a dot product?

In [71]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.70653645 0.641165   0.35237156 0.94902681 0.88994686]
 [0.57496928 0.85590985 0.28847181 0.32786988 0.51755424]
 [0.32858734 0.01239477 0.54837231 0.41371336 0.20200594]
 [0.17991803 0.82305184 0.90923784 0.24535142 0.70654656]
 [0.480041   0.06315365 0.47817607 0.15190362 0.55204152]]
[[0.13693911 0.63301391 0.38406785 0.82890014 0.29031983]
 [0.12426803 0.42505688 0.59735564 0.15625271 0.50117326]
 [0.92733495 0.49874799 0.21034091 0.40610949 0.22277222]
 [0.68696572 0.39885904 0.6943771  0.85317447 0.0164531 ]
 [0.3668627  0.10077923 0.62223873 0.6101574  0.41779978]]
diagonal of a dot product method 1 is.... [1.48163244 1.05458124 0.66191804 1.28742045 0.5106828 ]
diagonal of a dot product method 2 is.... [1.48163244 1.05458124 0.66191804 1.28742045 0.5106828 ]


# Q 13.How to find the most frequent value in an array?

In [70]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[3 6 5 1 6 4 0 2 0 8 6 1 0 4 1 6 4 8 7 1 2 3 3 0 2 8 1 0 4 6 5 5 1 2 2 7 2
 0 4 2 4 8 3 4 8 0 7 5 1 3]
0


#  Q14.How to get the n largest values of an array

In [69]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


# Q15.How to create a record array from a regular array?

In [64]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
